server {
    server_name fuel.shenthar.me;
    client_max_body_size 1m;

    include /etc/nginx/snippets/security-headers.conf;
    include /etc/nginx/snippets/rate-limit.conf;

    location / {
        proxy_pass http://127.0.0.1:9124;
        include /etc/nginx/snippets/proxy-params.conf;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/fuel.shenthar.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fuel.shenthar.me/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = fuel.shenthar.me) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name fuel.shenthar.me;
    return 404;
}